system:
  device: cuda
  num_workers: 16

dataset: cifar10

model: alexnet

optimization:
  epochs: 100
  batch_size: 512
  optimizer: adam
  optimizer_params:
    lr: 0.0001
    betas: [0.9, 0.999]
    eps: 0.00000001
    weight_decay: 0
  lr_scheduling: constant
  lr_scheduling_params: {}

logging:
  wandb: True
  save_dir: ../src/models/tmp_cifar10_alexnet_base