system:
  device: cuda:0
  num_workers: 16

dataset: cifar10
train_transforms:
  resize: -1
  random_crop:
    size: 32
    padding: 4
  horizontal_flip: True
  norm_mean: [0.4914, 0.4822, 0.4465]
  norm_std: [0.2023, 0.1994, 0.2010]
val_transforms:
  resize: -1
  random_crop: {}
  horizontal_flip: False
  norm_mean: [0.4914, 0.4822, 0.4465]
  norm_std: [0.2023, 0.1994, 0.2010]

model: resnet50_madry

optimization:
  epochs: 100
  batch_size: 512
  optimizer: sgd
  optimizer_params:
    lr: 0.01
    momentum: 0.9
    weight_decay: 0.01
    nesterov: True
  lr_scheduling: linear_warmup_cosine_decay
  lr_scheduling_params:
    warmup_start_lr: 0.00000001
    base_lr: 0.01
    warmup_steps: 30 # In epochs
    max_steps: 100 # In epochs
    eta_min: 0.00000001

logging:
  wandb: True
  save_dir: /home/gpogoncheff/Documents/research/align_interp/resnet50_cifar10_base_norm2
