system:
  device: cuda
  num_workers: 16

dataset: cifar10
train_transforms:
  resize: -1
  random_crop:
    size: 32
    padding: 4
  horizontal_flip: True
  norm_mean: [0.4914, 0.4822, 0.4465]
  norm_std: [0.2470, 0.2435, 0.2616]
val_transforms:
  resize: -1
  random_crop: {}
  horizontal_flip: False
  norm_mean: [0.4914, 0.4822, 0.4465]
  norm_std: [0.2470, 0.2435, 0.2616]

model: vgg19_cifar10

optimization:
  epochs: 150
  batch_size: 256
  optimizer: sgd
  optimizer_params:
    lr: 0.01
    momentum: 0.9
    weight_decay: 0.01
    nesterov: True
  lr_scheduling: linear_warmup_cosine_decay
  lr_scheduling_params:
    warmup_start_lr: 0.00000001
    base_lr: 0.01
    warmup_steps: 45 # In epochs
    max_steps: 150 # In epochs
    eta_min: 0.00000001

logging:
  wandb: True
  save_dir: ../src/models/checkpoints/cifar10_vgg19_cifar10_base
